### ISSUE TITLE
G30 "unavailable"

### ISSUE THREAD

**Issue by samwise22** [3ative/Eufy-RoboVac-to-HA#2]
I've tried to use T2118 as in your example and also T2252 which I'm pretty sure is the right model number for the G30.

**Comment by 3ative** [comment]
Sorry Sam, I can really answer questions about other models - The video & instructions are for my C30. 

However, there are a few people that have posed similar questions (_and found solutions_) - Check out their comments on this video on YouTube.
**Hint: look for the ones with the most replies.**

**Comment by samwise22** [comment]
Ok will do thanks. Might be helpful put that disclaimer in the top of your README if you don't intend it for other models?

**Comment by 3ative** [comment]
@samwise22 
Good luck. 
Thnx, good point - I'll pop something in there soon. Cheers 👍
